Repository Kusitms-29th-Soullive-C/frontend, pull requests merged in 2024-03, with the labels that each got.

#2 적합도 분석 시작화면 구현
  app/src/main/java/com/example/soullive/MainActivity.kt
  app/src/main/java/com/example/soullive/ui/fitness/FitnessFragment.kt
  app/src/main/java/com/example/soullive/ui/fitness/FitnessViewModel.kt
  app/src/main/java/com/example/soullive/ui/input_start/InputStartFragment.kt
  app/src/main/res/anim/move_up_down.xml
  app/src/main/res/drawable/bg_btn_radius_4dp.xml
  app/src/main/res/drawable/bg_gradient.xml
  app/src/main/res/drawable/ic_3d_logo.png
  app/src/main/res/drawable/ic_3d_logo.xml
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/font/pretendard_bold.ttf
  app/src/main/res/font/pretendard_medium.ttf
  app/src/main/res/layout/fragment_bookmark.xml
  app/src/main/res/layout/fragment_fitness.xml
  app/src/main/res/layout/fragment_input_start.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design, feat

#3 타겟층 화면 구현
  app/src/main/java/com/example/soullive/MainActivity.kt
  app/src/main/java/com/example/soullive/ui/input_start/InputStartFragment.kt
  app/src/main/java/com/example/soullive/ui/input_target/InputTargetFragment.kt
  app/src/main/res/color/btn_target_next_text_selector.xml
  app/src/main/res/color/btn_target_text_selector.xml
  app/src/main/res/drawable/bg_btn_target.xml
  app/src/main/res/drawable/bg_btn_target_next_selector.xml
  app/src/main/res/drawable/bg_btn_target_pressed.xml
  app/src/main/res/drawable/btn_target_border_selector.xml
  app/src/main/res/layout/fragment_input_start.xml
  app/src/main/res/layout/fragment_input_target.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: design, feat

#4 모델 검색 및 추가(input step4) 구현
  app/build.gradle.kts
  app/src/main/java/com/example/soullive/MainActivity.kt
  app/src/main/java/com/example/soullive/ui/input/InputStartFragment.kt
  app/src/main/java/com/example/soullive/ui/input/InputStep3Fragment.kt
  app/src/main/java/com/example/soullive/ui/input/InputStep5Fragment.kt
  app/src/main/java/com/example/soullive/ui/input_search/InputStep4Fragment.kt
  app/src/main/java/com/example/soullive/ui/input_search/SearchResultAdapter.kt
  app/src/main/java/com/example/soullive/ui/input_search/SelectedItemAdapter.kt
  app/src/main/res/drawable/bg_search_count_container.xml
  app/src/main/res/drawable/bg_search_edittext_focused.xml
  app/src/main/res/drawable/bg_search_edittext_normal.xml
  app/src/main/res/drawable/bg_search_field.xml
  app/src/main/res/drawable/bg_search_keyword.xml
  app/src/main/res/drawable/bg_search_results_container.xml
  app/src/main/res/drawable/bg_search_rounded_container.xml
  app/src/main/res/drawable/ic_goyoonjung.png
  app/src/main/res/drawable/ic_itsub.png
  app/src/main/res/drawable/ic_subtract.xml
  app/src/main/res/layout/fragment_input_step4.xml
  app/src/main/res/layout/item_search_keywords.xml
  app/src/main/res/layout/item_search_result.xml
  app/src/main/res/layout/item_search_selected.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: feat

#9 적합도 분석화면(하단바에서)
  app/src/main/res/drawable/bg_btn_fitness.xml
  app/src/main/res/drawable/bg_fitness_history.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_goto_analyze.png
  app/src/main/res/drawable/ic_qna.png
  app/src/main/res/layout/fragment_fitness.xml
  app/src/main/res/layout/fragment_input_start.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: design, feat

#7 Input(step3) 피드백 반영 수정
  app/src/main/java/com/example/soullive/ui/input_search/InputStep4Fragment.kt
  app/src/main/java/com/example/soullive/ui/input_search/SelectedItemAdapter.kt
  app/src/main/res/drawable/bg_btn_input_model_selector.xml
  app/src/main/res/layout/fragment_input_step4.xml
Labels: bug

#10 Output(step1) 분석결과, 유사모델추천 구현
  app/src/main/java/com/example/soullive/MainActivity.kt
  app/src/main/java/com/example/soullive/ui/input/InputStep5Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_step1/GroupedItemsAdapter.kt
  app/src/main/java/com/example/soullive/ui/output_step1/OutputModelAdapter.kt
  app/src/main/java/com/example/soullive/ui/output_step1/OutputStep1Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_step1/SimilarModelAdapter.kt
  app/src/main/res/drawable/bg_output_overlay.xml
  app/src/main/res/drawable/bg_output_rounded_btn.xml
  app/src/main/res/drawable/bg_output_rounded_image.xml
  app/src/main/res/drawable/bg_output_rounded_rank.xml
  app/src/main/res/drawable/bg_output_tab_selector.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_bookmark_purple.xml
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/drawable/ic_output4.jpg
  app/src/main/res/drawable/ic_output5.jpg
  app/src/main/res/drawable/ic_sohee.jpg
  app/src/main/res/layout/fragment_output_step1.xml
  app/src/main/res/layout/item_output_step1_detail.xml
  app/src/main/res/layout/item_output_step1_model.xml
  app/src/main/res/layout/item_output_step1_similar.xml
  app/src/main/res/layout/item_output_step1_spinner.xml
  app/src/main/res/layout/page_models_layout.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: feat

#20 상세분석 화면 구현
  app/src/main/java/com/example/soullive/MainActivity.kt
  app/src/main/java/com/example/soullive/ui/fitness/FitnessFragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/DialogDownloadFragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailFragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView1Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView2Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView3Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView4Fragment.kt
  app/src/main/res/color/bg_checkbox_selector.xml
  app/src/main/res/drawable/bg_bookmark_selector.xml
  app/src/main/res/drawable/bg_grey500_10dp.xml
  app/src/main/res/drawable/bg_grey600_4dp.xml
  app/src/main/res/drawable/bg_grey700_8dp.xml
  app/src/main/res/drawable/bg_grey800_0dp.xml
  app/src/main/res/drawable/bg_grey800_12dp.xml
  app/src/main/res/drawable/bg_grey800_12dp_border_grey700_2dp.xml
  app/src/main/res/drawable/bg_purple400_10dp.xml
  app/src/main/res/drawable/bg_tab_selector.xml
  app/src/main/res/drawable/ic_advertiesement_arrow.xml
  app/src/main/res/drawable/ic_advertisement1.png
  app/src/main/res/drawable/ic_advertisement2.png
  app/src/main/res/drawable/ic_advertisement3.png
  app/src/main/res/drawable/ic_advertisement4.png
  app/src/main/res/drawable/ic_advertisement5.png
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_bookmark_purple.xml
  app/src/main/res/drawable/ic_detail_follower_graph.png
  app/src/main/res/drawable/ic_detail_model_issue.png
  app/src/main/res/drawable/ic_detail_model_topic.png
  app/src/main/res/drawable/ic_detail_strategy1.png
  app/src/main/res/drawable/ic_detail_strategy2.png
  app/src/main/res/drawable/ic_detail_strategy3.png
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_home_p500.xml
  app/src/main/res/drawable/ic_mypage_p500.xml
  app/src/main/res/layout/dialog_download.xml
  app/src/main/res/layout/fragment_fitness.xml
  app/src/main/res/layout/fragment_ouput_detail_view1.xml
  app/src/main/res/layout/fragment_output_detail.xml
  app/src/main/res/layout/fragment_output_detail_view2.xml
  app/src/main/res/layout/fragment_output_detail_view3.xml
  app/src/main/res/layout/fragment_output_detail_view4.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle.properties
Labels: design, feat

#21 Revert "상세분석 화면 구현"
  app/src/main/java/com/example/soullive/MainActivity.kt
  app/src/main/java/com/example/soullive/ui/fitness/FitnessFragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/DialogDownloadFragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailFragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView1Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView2Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView3Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_detail/OutputDetailView4Fragment.kt
  app/src/main/res/color/bg_checkbox_selector.xml
  app/src/main/res/drawable/bg_bookmark_selector.xml
  app/src/main/res/drawable/bg_grey500_10dp.xml
  app/src/main/res/drawable/bg_grey600_4dp.xml
  app/src/main/res/drawable/bg_grey700_8dp.xml
  app/src/main/res/drawable/bg_grey800_0dp.xml
  app/src/main/res/drawable/bg_grey800_12dp.xml
  app/src/main/res/drawable/bg_grey800_12dp_border_grey700_2dp.xml
  app/src/main/res/drawable/bg_purple400_10dp.xml
  app/src/main/res/drawable/bg_tab_selector.xml
  app/src/main/res/drawable/ic_advertiesement_arrow.xml
  app/src/main/res/drawable/ic_advertisement1.png
  app/src/main/res/drawable/ic_advertisement2.png
  app/src/main/res/drawable/ic_advertisement3.png
  app/src/main/res/drawable/ic_advertisement4.png
  app/src/main/res/drawable/ic_advertisement5.png
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_bookmark_purple.xml
  app/src/main/res/drawable/ic_detail_follower_graph.png
  app/src/main/res/drawable/ic_detail_model_issue.png
  app/src/main/res/drawable/ic_detail_model_topic.png
  app/src/main/res/drawable/ic_detail_strategy1.png
  app/src/main/res/drawable/ic_detail_strategy2.png
  app/src/main/res/drawable/ic_detail_strategy3.png
  app/src/main/res/drawable/ic_download.xml
  app/src/main/res/drawable/ic_home_p500.xml
  app/src/main/res/drawable/ic_mypage_p500.xml
  app/src/main/res/layout/dialog_download.xml
  app/src/main/res/layout/fragment_fitness.xml
  app/src/main/res/layout/fragment_ouput_detail_view1.xml
  app/src/main/res/layout/fragment_output_detail.xml
  app/src/main/res/layout/fragment_output_detail_view2.xml
  app/src/main/res/layout/fragment_output_detail_view3.xml
  app/src/main/res/layout/fragment_output_detail_view4.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  gradle.properties
Labels: bug

#17 Output(step1) 다시시작하기 팝업 & 유사모델 오류 수정
  app/src/main/java/com/example/soullive/ui/output_step1/OutputDialogFragment.kt
  app/src/main/java/com/example/soullive/ui/output_step1/OutputStep1Fragment.kt
  app/src/main/java/com/example/soullive/ui/output_step1/SimilarModelAdapter.kt
  app/src/main/res/drawable/bg_dialog_btn_left.xml
  app/src/main/res/drawable/bg_dialog_btn_right.xml
  app/src/main/res/drawable/bg_dialog_rounded.xml
  app/src/main/res/layout/fragment_output_dialog.xml
  app/src/main/res/layout/fragment_output_step1.xml
  app/src/main/res/layout/item_output_step1_similar.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: bug, feat

#16 검색 페이지 레이아웃
  app/src/main/java/com/example/soullive/ui/home/SearchFragment.kt
  app/src/main/res/drawable/model_goyunjung.jpg
  app/src/main/res/drawable/model_jeonjongseo.jpg
  app/src/main/res/drawable/model_jisu.jpg
  app/src/main/res/drawable/model_leejubin.jpg
  app/src/main/res/drawable/model_suji.jpg
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/strings.xml
Labels: design

#18 Output(Search) - 검색 기능 구현
  app/src/main/java/com/example/soullive/ui/output_search/OutputSearchAdapter.kt
  app/src/main/java/com/example/soullive/ui/output_search/OutputSearchFragment.kt
  app/src/main/java/com/example/soullive/ui/output_step1/OutputStep1Fragment.kt
  app/src/main/res/drawable/ic_gosu.png
  app/src/main/res/layout/fragment_output_search.xml
  app/src/main/res/layout/item_search_model.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: feat

#19 Home(Search) - 검색 기능 구현
  app/src/main/java/com/example/soullive/ui/home/HomeFragment.kt
  app/src/main/java/com/example/soullive/ui/home_search/HomeSearchAdapter.kt
  app/src/main/java/com/example/soullive/ui/home_search/SearchFragment.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/navigation/mobile_navigation.xml
  app/src/main/res/values/strings.xml
Labels: feat
